---
# tasks file for app-installer

- name: Install required Applications
  # su -
  # apt-get install -y <apps>
  ansible.builtin.apt:
    name: '{{ item }}'
    state: latest
  with_items:
    - bmon
    - git
    - htop
    - vim
