---
- name: Deployment of a Raspberry Pi Proxmox Cluster
  hosts: nodes
  become: true
  become_method: sudo
  serial:
  - 1

  roles:
    # upgrade method must be defined in group vars
    - host-upgrader
    - app-installer
    #- proxmox-deployment
    