---
- name: Reboot the whole cluster
  hosts: nodes
  become: true
  become_method: sudo
  serial:
  - 1

  tasks:
  - name: Reboot target host/s
    ansible.builtin.reboot:
      # Reboot timeout: Maximum seconds to wait for machine to reboot and respond to a test command.
      reboot_timeout: 360

  - name: Ping target host/s
    ansible.builtin.ping:
