---
- name: Reboot the whole cluster
  hosts: nodes
  become: true
  become_method: sudo
  
  tasks:
  - name: Reboot a slow machine that might have lots of updates to apply
    ansible.builtin.reboot:
      reboot_timeout: 0